<?php

    function globlog_signature_block_info()
    {
        $blocks['globlog_signature'] = array(
            'info' => t('Signatures')
        );

        return $blocks;
    }

    function globlog_signature_block_view($delta = '') {
        // modified block view
        $block = array();
        // name list
        $n1 = "Ale";
        $n2 = "Eze";
        $n3 = "Fede";
        $n4 = "Gonza";
        $n5 = "Luca";
        $names = $n1.", ".$n2.", ".$n3.", ".$n4.", ".$n5;
        $base_path= base_path();
        $img= $base_path . "sites/all/modules/globlog_signature/logo-Globant.png";

        switch ($delta) {
        case 'globlog_signature':
            // content to display
            $block['content'] = array(
                '#markup' => '<div>
                                <style type="text/css">
                                    #wrap {
                                        width:1100px;
                                        margin:0 auto;
                                    }
                                    #left_col {
                                        float:left;
                                        width:300px;
                                    }
                                    #right_col {
                                        float:right;
                                        width:120px;
                                    }
                                </style>

                                <div id="wrap">
                                    <div id="left_col">
                                        Made by</br>
                                        '. $names .'
                                    </div>
                                    <div id="right_col">
                                        Powered by</br>
                                        <img src="'. $img .'
                                        "</img>
                                    </div>
                                </div><br></br>
                            </div>',
            );
            break;
        }

        return $block;
    }
