<?php

    function globlog_signature_block_info()
    {
        $blocks['globlog_signature'] = array(
            'info' => t('Signatures')
        );

        return $blocks;
    }

    function globlog_signature_block_view($delta = '') {
        // modified block view
        $block = array();
        // name list
        $n1 = "<li>Ale</li>";
        $n2 = "<li>Eze</li>";
        $n3 = "<li>Fede</li>";
        $n4 = "<li>Gonza</li>";
        $n5 = "<li>Luca</li>";
        $names = $n1.$n2.$n3.$n4.$n5;
        $base_path= base_path();
        $img= $base_path . "sites/all/modules/globlog_signature/logo-Globant.png";

        switch ($delta) {
        case 'globlog_signature':
            // content to display
            $block['content'] = array(
                '#markup' => '<div>
                                <style type="text/css">
                                    #wrap {
                                        width:1100px;
                                        margin:0 auto;
                                    }
                                    #left_col {
                                        float:left;
                                        width:300px;
                                    }
                                    #right_col {
                                        float:right;
                                        width:120px;
                                    }
                                </style>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <!--COLUMNA IZQUIERDA-->
                                    <div id="left_col">
                                        Made by</br>
                                        <ul>
                                        '. $names .'
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <!--COLUMNA DERECHA-->
                                    <div id="right_col">
                                        Powered by</br>
                                        <img src="'. $img .'
                                        "</img>
                                    </div>
                                </div>
                            </div>',
            );
            break;
        }

        return $block;
    }
